title: Hung The's homepage
author: Hung The
email: hungntheit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hung The
  Software Engineer
  Java Developer
# social links
github_username: hungtheit

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal